config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :movies, except: [:edit] do
    resources :orders, except: [:show, :index, :edit]
  end

  resources :users do
    resources :orders
  end

  root 'movies#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :user
  belongs_to :order

  has_attached_file :image, styles: { medium: "300x300>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_one :movie
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :movies
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = current_user.movies.build
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:name, :desc, :movie_length, :director, :image)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :set_movie, except: [:index]
  before_action :authenticate_user!

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.movie_id = @movie.id
    @order.user_id = current_user.id
    @order.value = @movie.price

    respond_to do |format|
      if @order.save
        format.html { redirect_to @movie, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :lastname, :address, :value)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # POST /orders
  # POST /orders.json

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieBox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="navbar navbar-dark navbar-expand-lg bg-dark">
  <a class="navbar-brand" href="#">Movie Box</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: 'nav-link' %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "New movie", new_movie_path, class: 'nav-link' %>
        </li>
        <li>
          <%= link_to "Account", edit_user_registration_path,  class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, class: 'nav-link', method: 'delete' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Movie Box</h1>
    <p class="lead">Browse, order and watch movie. Whatever you want!</p>
  </div>
</div>


<%= yield %>


<footer>
  <p>Application by: Mariusz. &copy 2018</p>
</footer>
</body>
</html>

app/views/movies/_form.html.erb
 <%= form_for @movie, html: { multipart: true }, class: 'form-control' do |f| %>
    <% if @movie.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

        <ul>
        <% @movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :desc %><br>
      <%= f.text_area :desc, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :movie_length %><br>
      <%= f.text_field :movie_length, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :director %><br>
      <%= f.text_field :director, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :image %><br>
      <%= f.file_field :image, class: 'form-control' %>
    </div>
    <div class="actions">
      <%= f.submit class: 'form-control' %>
    </div>
  <% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<div class="container">
  <h1>Listing Movies</h1>

  <div class="row movies">
    <% @movies.each do |movie| %>
      <div class="col-md-4">
        <div class="card" style="width: 18rem;">
          <%= image_tag movie.image.url(:medium), class: 'card-img-top' %>
          <div class="card-body">
            <h5 class="card-title"><%= movie.name %></h5>
            <p class="card-text"><%= movie.desc %></p>
            <%= link_to 'More details', movie, class: 'btn btn-primary btn-movie-details' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/movies/new.html.erb
<div class="container">

  <div class="card card-login">
    <div class="card-header">
      New Movie
    </div>
    <div class="card-body">
      <div class="card-body">
        <%= render 'form' %>

        <%= link_to 'Back', movies_path %>
      </div>
    </div>
  </div>
</div>

app/views/movies/show.html.erb
<div class="container">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">  <%= @movie.name %></h5>
      <div class="card-body card-movie">
        <div class="movie-info">

          <%= image_tag @movie.image.url(:medium) %>

          <div class="movie-text">
            <p>
              <strong>Desc:</strong>
              <%= @movie.desc %>
            </p>

            <p>
              <strong>Movie length:</strong>
              <%= @movie.movie_length %>
            </p>

            <p>
              <strong>Director:</strong>
              <%= @movie.director %>
            </p>
          </div>
        </div>

        <div class="movie-buttons">
          <%= link_to 'Order that movie', new_movie_order_path(@movie.id), class: 'btn btn-danger' %>
          <%= link_to 'Back', movies_path, class: 'btn btn-primary' %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/orders/_form.html.erb
<%= form_for([@movie, @order]) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address, class:'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-danger'%>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Address</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.lastname %></td>
        <td><%= order.address %></td>
        <td><%= order.value %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/orders/new.html.erb
<div class="container">

  <div class="card card-login">
    <div class="card-header">
     Order now!
    </div>
    <div class="card-body">
      <div class="card-body">
        <%= render 'form' %>

        <%= link_to 'Back', new_movie_order_path %>
      </div>
    </div>
  </div>

</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @order.lastname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Value:</strong>
  <%= @order.value %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>